server:
  port: ${SERVER_PORT:8001}

spring:
  application:
    name: PAYMENT-SERVICE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/bookstore_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:PaSSworD}

  security:
    jwt:
      issuer-uri: http://auth-server:3001/oauth2/jwks
      public-key: classpath:jwt-signing-public-key.txt

  service:
    stripeKey: pk_test_51MeLJiCj68nmJvkeUmSmytgvIeeWY1NqF2XCne0h5iot0dn5Y1AiNiVbeWcwkLloK1AQgHqHlPNJBkKKfVXNNkor00uu3qOOGp
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost:8761}/eureka/
    registerWithEureka: true
    fetch-registry: true #eureka discovery is enabled in this profile
  instance:
    prefer-ip-address: false

