server:
  port: ${SERVER_PORT:8761}

eureka:
  application:
    name: eureka-discovery-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  client:
    registerWithEureka: false   #telling the server not to register itself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
  instance:
    prefer-ip-address: false