server:
  port: ${SERVER_PORT:8765}

spring:
  application:
    name: API-GATEWAY-SERVICE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=2
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/catalogFallBack
        - id: billing-service
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/api/billing/**
          filters:
            - StripPrefix=2
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=2
        - id: auth-server
          uri: lb://AUTH-SERVER-2
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost:8761}/eureka/
    registerWithEureka: true
    fetch-registry: true #eureka discovery is enabled in this profile
  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"